# Generated by Django 6.0 on 2025-12-18 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('SEV1', 'SEV1'), ('SEV2', 'SEV2'), ('SEV3', 'SEV3'), ('SEV4', 'SEV4')], max_length=8)),
                ('status', models.CharField(choices=[('INVESTIGATING', 'Investigating'), ('IDENTIFIED', 'Identified'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved')], default='INVESTIGATING', max_length=32)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='incidents.incident')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status_at_time', models.CharField(choices=[('INVESTIGATING', 'Investigating'), ('IDENTIFIED', 'Identified'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved')], max_length=32)),
                ('created_by_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('detection', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postmortem', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=16)),
                ('postmortem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='incidents.postmortem')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('INCIDENT', 'Incident')], default='GLOBAL', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='incidents.incident')),
            ],
        ),
    ]
